-- Agency Report Kit production database
-- Run this in Supabase SQL Editor after enabling Google Auth.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  plan text not null default 'free' check (plan in ('free','pro')),
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  event text not null,
  source text,
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.events enable row level security;
alter table public.reports enable row level security;

create policy "users read own profile" on public.profiles
for select using (auth.uid() = id);

create policy "users update own profile" on public.profiles
for update using (auth.uid() = id);

create policy "users insert own events" on public.events
for insert with check (auth.uid() = user_id);

create policy "users read own events" on public.events
for select using (auth.uid() = user_id);

create policy "users manage own reports" on public.reports
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Create profile automatically after Google sign-in.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id,email,full_name,avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- ADMIN NOTE:
-- Do not expose a service-role key in the frontend.
-- For an actual admin dashboard, create a server-side Edge Function or
-- admin-only RPC that checks an allowlisted admin user ID/email.
